name: "AssetWise"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

#iOS
# version: 1.48.0+1

#Android
version: 1.1.0+2025022701

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^5.0.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_file_saver: ^0.8.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  gal: ^2.3.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^8.2.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.5
  webview_flutter: ^4.10.0
  widgets_to_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.4
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
