name: "AssetWise"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

#iOS
version: 1.48.0+1

#Android
#version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^5.0.0
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  flutter_widget_from_html: ^0.15.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.4
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
