#!/bin/bash

# สคริปต์สำหรับสลับ environment ของโปรเจค AssetWise
# วิธีใช้: ./scripts/env.sh [dev|prod|uat]

set -e

ENV=${1:-dev}
URL_CONST_FILE="lib/src/consts/url_const.dart"

case $ENV in
    "dev")
        BASE_URL="https://dev-superapp-api.assetwise.co.th"
        echo "🔄 กำลังตั้งค่า Development Environment..."
        ;;
    "prod")
        BASE_URL="https://superapp-api.assetwise.co.th"
        echo "🚀 กำลังตั้งค่า Production Environment..."
        ;;
    "uat")
        BASE_URL="https://uat-superapp-api.assetwise.co.th"
        echo "🧪 กำลังตั้งค่า UAT Environment..."
        ;;

    *)
        echo "❌ Environment ไม่ถูกต้อง"
        echo "กรุณาใช้: ./scripts/env.sh [dev|prod|uat]"
        exit 1
        ;;
esac

# สร้างไฟล์ url_const.dart ใหม่
cat > $URL_CONST_FILE << EOF
// Auto-generated by env.sh script
// Current Environment: $ENV

const BASE_URL = '$BASE_URL';

// Other environments (commented):
// DEV: https://dev-superapp-api.assetwise.co.th
// PROD: https://superapp-api.assetwise.co.th
// UAT: https://uat-superapp-api.assetwise.co.th
EOF

echo "✅ อัปเดต $URL_CONST_FILE แล้ว"
echo "📡 BASE_URL: $BASE_URL"
echo ""
echo "🔧 คำสั่งสำหรับ build:"
echo "   Flutter: flutter build apk --dart-define=ENVIRONMENT=$ENV"
echo "   iOS: flutter build ios --dart-define=ENVIRONMENT=$ENV"